apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 11cj
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: 11cj
            args:
            - /bin/sh
            - -c
            - date;
          restartPolicy: OnFailure
