apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvgce1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: gce
  gcePersistentDisk:
    pdName: k8-data-disk
    fsType: ext4
